### PR TITLE
db create user

### PR DESCRIPTION
**Pull request by Auragen-dev**
Added a function which will create new users. Returns a boolean depending on success or failure

### CODE REVIEW

**Comment by ws265660** [comment]
Tested it out and there should now be an account called LeeText with a password of "password".
image

**Comment by Auragen-dev** [comment]
Indeed there is

**Comment by Auragen-dev** [comment]
image

**Comment by ws265660** [comment]
Awesome. Then it is good to go. I will say to hash the passwords in the database so they are 100% safe.

**Comment by Auragen-dev** [comment]
I'll write a separate function to do that later

**Pull request merged**
