### PR TITLE
Feature frontend

### PR DESCRIPTION
**Pull request by ws265660**
Pull request of the first draft of the forms.

### CODE REVIEW

**Comment by ws268644** [comment]
Are you doing the page layout first before the functionality?

**Comment by ws265660** [comment]
> Are you doing the page layout first before the functionality?

There will be basic functionality, simple navigation and string handling. I'll leave sections open for sql implementation.

**Comment by Auragen-dev** [comment]
Ok. Because none of the buttons seem to work when run it.

**Comment by ws265660** [comment]
> Ok. Because none of the buttons seem to work when run it.

I think that's another issue with the push pull issues we had earler. I mentioned in uni that the way the buttons worked on that version was different from the one I have locally here. I'll fix up a few things and push again. Should I edit the gitignore on my end and see if that helps?

**Comment by Auragen-dev** [comment]
If you know how .gitingore works then go for it. If you don't know what you're doing I wouldn't try it.

**Comment by Auragen-dev** [comment]
The back button on the events page doesn't work. 
The profile back button takes us to a different page. I think the profile page was supposed to go to that page initially instead of this data table.

**Comment by ws265660** [comment]
Ah ok, not a problem. That should be an easy fix.

**Comment by Auragen-dev** [comment]
Those buttons are working now. I just noticed the Tracks and Quit buttons on the main page don't work.

**Comment by Auragen-dev** [comment]
All looks good. I'm going to merge it.

**Pull request merged**
