### PR TITLE
Function unit testing

### PR DESCRIPTION
**Pull request by ws265660**
Added logout and updated the new events page with more information to input.

### CODE REVIEW

**Comment by Auragen-dev** [comment]
I'm getting a lot of Build errors all cantered around the clsDatabase class. Specifically, when it's mentioned at the top of the file (i.e "using projectChocobo.clsDatabase").
The login function is also throwing up an error when I try running it
image

**Comment by Auragen-dev** [comment]
I got rid of the static keyword, tried running it and typed it back in. It works now

**Comment by ws265660** [comment]
> I got rid of the static keyword, tried running it and typed it back in. It works now

That is very odd.

**Comment by Auragen-dev** [comment]
The events page has a few unnecessary additions.
We're not tracking attendees or spectators in the database.
We're not tracking how many racers are in the race explicitly. There's not a number stored like this.

**Comment by Auragen-dev** [comment]
Also, we don't actually have an event description field in the database.

**Comment by ws265660** [comment]
You want me to remove it?

**Comment by ws265660** [comment]
Can we add in a field for it?

**Comment by ws265660** [comment]
> 

Can do

**Comment by ws265660** [comment]
Pushed the updates. Any new changes will need to be in a new branch, so if everything looks good, I'll merge

**Comment by Auragen-dev** [comment]
Looks fine so far. We just need to link the database functions up. But I'll handle that in another branch. Merge away!

**Comment by ws265660** [comment]
> Looks fine so far. We just need to link the database functions up. But I'll handle that in another branch. Merge away!

Will do. Merged and made a new branch, feature_EventsUpdate

**Pull request merged**
