### PR TITLE
Feature frontend role assign

### PR DESCRIPTION
**Pull request by ws265660**
Added in account creation and role assignment.

### CODE REVIEW

**Comment by Auragen-dev** [comment]
There's no admin option in the combobox.

**Comment by Auragen-dev** [comment]
There's only a button for adding a racer

**Comment by ws265660** [comment]
image
Added Admin Role
image

**Comment by Auragen-dev** [comment]
Ok. I'm going to test it now. I'll screenshot what happens.

**Comment by Auragen-dev** [comment]
image
It's kicking up errors. I have a feeling this is to do with the role assign function. I'll create a sub branch to see if I can fix it.

**Comment by Auragen-dev** [comment]
image
It's defiantly the role assign function as the form is adding users first.

**Comment by Auragen-dev** [comment]
image

I've fixed the combo box issue. The function now just changes the strings to lower case to make it safer. But now I got it working the database is kicking up issues. It seems the username check is working but also not? I'm gonna look into this.

**Comment by ws265660** [comment]
I need to you make a stored procedure for the following:
>racer names
>Steward names
>car names
>user login names

**Comment by Auragen-dev** [comment]
Procedures have been added. In order they are called:
getRacerNames
getStewardUsernames
getCarNames
getAllUsernames

**Comment by Auragen-dev** [comment]
image
I'm still getting this error. I'm gonna look into it

**Comment by Auragen-dev** [comment]
image
image
The first image is the Admin table. The second is the users page. You'll notice the user ID's match. User 19 was added using a redone procedure and User 30 was added via windows form program.

The problem to my knowledge was that the procedure was expecting a different kind of data. It was expecting an ID and we were feeding it a username. 
The username check function was included in one of the errors being thrown up so I commented it out where I could. I'm going to try and reintroduce them back into the program.

**Comment by ws265660** [comment]
There are merge conflicts with clsDatabase.

**Comment by Auragen-dev** [comment]
All looks pretty good. I'll resolve the merge conflict

**Comment by Auragen-dev** [comment]
All done

**Pull request merged**
